# Publish a Python Package

name: Publish Packages on Release

on:
  release:
    types: [ created ]

jobs:
  publish:
    runs-on: ubuntu-latest
    environment:
      name: deployment

    permissions:
      contents: read
      packages: write
      id-token: write

    name: Publish Release
    steps:
      - uses: actions/checkout@v5
        with:
          persist-credentials: false

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.14"

      - name: Install build requirements
        run: python -m pip install build setuptools twine --user

      - name: Build a binary wheel and a source tarball
        run: python -m build --sdist --wheel --outdir dist/

      - name: Sign Distributions
        uses: dk96-os/gh-action-sigstore-python@c2bab25c752726c7cbf0a5939180f5bea142677d # v4.0
        with:
          inputs: >-
            ./dist/*.tar.gz
            ./dist/*.whl

      - name: Cleanup Dist Directory after signing
        run: |
          cd dist
          echo "Removing files that do not match '*.tar.gz' or '*.whl'"
          for file in *; do
            if [[ ! "$file" == *".tar.gz" ]] && [[ ! "$file" == *".whl" ]]; then
              echo "Removing: $file"
              rm "$file"
            fi
          done
          cd ../

      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@ed0c53931b1dc9bd32cbe73a98c7f6766f8a527e # v1.13.0
        with:
          print-hash: true
